### PR TITLE
HTML in error message

### PR DESCRIPTION
**Pull request by aevaldas**
Added HTML support in error message. #25

### CODE REVIEW

**Comment by tonickkozlov** [comment]
@aevaldas Thanks a lot for your commits!
Could you please update the Readme as well?

Cheers!

**Comment by DhruvAerosol** [comment]
@aevaldas waiting for your updates.

**Comment by aevaldas** [comment]
@tonickkozlov updated ✌️

**Comment by DhruvAerosol** [comment]
@tonickkozlov Please merge new PR.

**Comment by DhruvAerosol** [comment]
> @tonickkozlov Please merge new PR.

Waiting..

**Comment by tonickkozlov** [comment]
@DhruvAerosol I'm working on an end-to-end test right now to make sure the change is working fine, for now you can use the code from this branch

**Comment by DhruvAerosol** [comment]
@aevaldas i am stuck in this:
`:error-message="'Sorry, <a>https://twitter.com/'+i.screen_name+'/status/'+i.tweet_id+'</a> can not be displayed because it is either private or deleted'"`
Not getting URL.

**Comment by aevaldas** [comment]
@DhruvAerosol you had to use `feature/link-in-error-message` branch at that moment.
I've merged `feature/link-in-error-message` into my `master` branch, so it should work for you.

**Comment by tonickkozlov** [comment]
Hi @aevaldas . Sorry for delay and thanks for your changes. I've pulled them into by branch, added tests with puppeteer and merged as part of https://github.com/tonickkozlov/vue-tweet-embed/pull/40 

🎉🎉🎉 These changes are now part of `v2.4.0` 🎉🎉🎉 

@DhruvAerosol you can update your package.json to track the new version

**Pull request closed without merging**
